# =============== Project Configuration ===============
language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - build-tools-27.0.3
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - extra-android-support
    
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


# =============== VM configuration ===============
jdk:
    - oraclejdk8

sudo: false


# =============== Before ===============
before_install: 
    - yes | sdkmanager "platforms;android-27" # see https://stackoverflow.com/a/47726910/3828773
    - chmod +x gradlew


# =============== Running ===============
script:
    - ./gradlew :clean :pushpixl:build


# =============== After ===============
after_success:
    - ./gradlew :pushpixl:cobertura :pushpixl:coveralls
    - ./gradlew :pushpixl:bintrayUpload